server_url: ''
incrementalbuild_url: 'https://webhook.gatsbyjs.com/hooks/benchmarks/publish/drupal/4096/231ac02b-f1d7-4a42-a59a-dcf038a309f5,https://webhook.staging.gtsb.io/hooks/benchmarks/publish/drupal/4096/231ac02b-f1d7-4a42-a59a-dcf038a309f5'
build_published: 1
preview_entity_types:
  node: node
  block_content: 0
  comment: 0
  contact_message: 0
  file: 0
  path_alias: 0
  shortcut: 0
  taxonomy_term: 0
  user: 0
  menu_link_content: 0
secret_key: ''
legacy_preview_url: 0
